CREATE DATABASE IF NOT EXISTS laravel;
CREATE DATABASE IF NOT EXISTS laravel_test;

GRANT ALL PRIVILEGES ON laravel.* TO 'laravel'@'%';
GRANT ALL PRIVILEGES ON laravel_test.* TO 'laravel'@'%';

FLUSH PRIVILEGES;
